name: Pull request CI
on: [pull_request]
jobs:
    python-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: chartboost/ruff-action@v1
              with:
                changed-files: 'true'
    python-format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: chartboost/ruff-action@v1
              with:
                args: 'format --check'
                changed-files: 'true'
    pytest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - run: |
                curl -LsSf https://astral.sh/uv/install.sh | sh
                uv pip install --system -r requirements.txt
            - run: pytest tests/

